export { default as Header } from './Header'
export { default as Aboutme } from './Aboutme'
export { default as Education } from './Education'
export { default as Work } from './Work'
export { default as Publications } from './Publications'
export { default as Other } from './Other'
export { default as Footer } from './Footer'
export { default as Sidebar } from './Sidebar'
